apiVersion: v1
kind: Service
metadata:
  name: ms-template
  namespace: qa
spec:
  selector:
    app: ms-template
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer